In [1]:
import numpy as np
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
x=np.linspace(1,10,10)
print(x)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [5]:
x=np.linspace(1,20,3)
print(x)

[ 1.  10.5 20. ]


In [6]:

x=np.linspace(10,20,5,endpoint=True)
print(x)

[10.  12.5 15.  17.5 20. ]


In [7]:
x=np.linspace(10,20,5,endpoint=True,retstep=True)
print(x)

(array([10. , 12.5, 15. , 17.5, 20. ]), 2.5)


In [8]:
x=np.linspace(10,20,5,endpoint=False,retstep=True)
print(x)

(array([10., 12., 14., 16., 18.]), 2.0)
