In [2]:
import numpy as np

# numpy.random.randint()

x=np.random.randint(5,size=10)
print(x)

[3 2 0 4 2 0 4 4 1 3]


In [3]:
#生成[low,high)范围的随机整数
y=np.random.randint(5,10,size=10)
print(y)

[7 8 5 7 5 6 9 9 6 6]


In [4]:
#生成[low,high)范围的 2*4 的随机整数
z=np.random.randint(5,10,size=(2,4))
print(z)

[[9 5 9 5]
 [8 7 9 5]]


In [28]:
# randn 函数返回一个或一组样本，具有标准正态分布
x=np.random.randn()
print(x)
y=np.random.randn(2,4)
print(y)
z=np.random.randn(2,3,4)
print(z)

0.9559373138644487
[[-0.29888735 -0.15064431  1.67482279  0.51677502]
 [-1.01364875 -0.18129468 -0.24130322  1.1864717 ]]
[[[-1.77780675 -1.47351148 -1.36324218  0.82254564]
  [-0.95397964 -0.27271772  0.33947301 -0.81283155]
  [ 0.12434248  0.64186706  0.92191209  0.78878495]]

 [[ 0.24944417 -0.34125132  0.58724157  0.29457047]
  [ 1.0164185   1.16124022  0.52531038 -0.65868662]
  [ 0.84133099 -0.84359184 -0.77327327  1.02874048]]]


In [34]:
# np.random.normal()的使用
#正太分布（高斯分布）loc：期望 scale：方差 size 形状
print(np.random.normal(loc=3,scale=4,size=(2,2,3)))

[[[-0.69322943  2.79459347  0.8896001 ]
  [-0.80429268 -5.0545895   2.2593509 ]]

 [[ 6.61976472  1.46264291 -0.35777926]
  [ 6.24969776  0.63739791  2.64296104]]]
