In [2]:
import numpy as np

x1=np.random.randint(10,size=6)
print(x1)


[1 4 9 8 3 8]
[[2 0 1 7]
 [4 5 5 8]
 [3 3 3 0]]


In [3]:
x2=np.random.randint(10,size=(3,4))
print(x2)

[[9 9 3 1]
 [9 0 0 4]
 [1 9 2 2]]


In [6]:
x3=np.random.randn(3,4,5)
print(x3)
print('ndim 属性'.center(20,'*'))
print('ndim:',x1.ndim,x2.ndim,x3.ndim)
print('shape 属性'.center(20,'*'))
print('shape:',x1.shape,x2.shape,x3.shape)
print('dtype 属性'.center(20,'*'))
print('dtype:',x1.dtype,x2.dtype,x3.dtype)
print('size 属性'.center(20,'*'))
print('size:',x1.size,x2.size,x3.size)
print('itemsize 属性'.center(20,'*'))
#一个字节是 8 位
print('itemsize:',x1.itemsize,x2.itemsize,x3.itemsize)

[[[ 0.59051181 -0.88697589 -0.14419974 -0.56299908  0.34905304]
  [ 0.08186111 -0.48986794 -0.29215309 -0.43077108 -0.29751567]
  [ 1.23397168  1.15451378  0.94628973 -0.86606515  0.61655874]
  [-1.62710168 -0.57067443  0.04405495  0.26093862 -0.46613441]]

 [[-0.41667877  0.52936791  0.03109313 -1.10752507  2.20633374]
  [-1.67732011 -0.64926868 -0.30509738  1.32818022 -0.21113351]
  [-1.22386571  0.96026257 -0.00320779  0.03587499 -1.0615224 ]
  [ 1.55959671 -0.42004     0.6798915   2.614301   -1.53481337]]

 [[ 0.54820195 -0.43586157  0.33684886  0.62654498 -1.9297471 ]
  [ 1.41788215 -0.78762988 -1.23631325  0.07376466 -1.10898728]
  [ 0.34177341  0.74014035  0.18157024  0.07923013  1.98829993]
  [ 0.35555384  0.31734489  0.2627705   0.83675654  1.019709  ]]]
******ndim 属性*******
ndim: 1 2 3
******shape 属性******
shape: (6,) (3, 4) (3, 4, 5)
******dtype 属性******
dtype: int32 int32 float64
******size 属性*******
size: 6 12 60
****itemsize 属性*****
itemsize: 4 4 8


In [9]:
a = np.zeros(5, dtype = float, order = 'C')
print(a)

[0. 0. 0. 0. 0.]


In [23]:
# 有"C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元 素的顺序。
b = np.zeros([3,2], dtype = float, order = 'F')
print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
